### ISSUE TITLE
PlayerJoinedEvent fired for each player on a server client is joining to

### ISSUE THREAD

**Issue by Tomasan7** [JsMacros/JsMacros#66]
When you join a server, the PlayerJoinedEvent is fired for each player that is already on the server (may be desired behavior, in that case, I would like to know how to fire only for new joining players)

This is probably because the event is fired on add player packet, which is sent as said.

**Comment by wagyourtail** [comment]
this is expected behavior. I try to filter it to new players by uuid already https://github.com/JsMacros/JsMacros/blob/b58159910fda307ab47d8c9ac698affe682342ae/common/src/main/java/xyz/wagyourtail/jsmacros/client/mixins/events/MixinClientPlayNetworkHandler.java#L63 so your server's doing weird stuff

**Comment by Gjum** [comment]
Some servers use a plugin for a custom sorting order on the player list (for example, Better TabList Plus); instead of real accounts, it uses "Slots" with non-player UUIDs; in that case, you can only rely on the displayName.
I'm not sure what approach JsMacros could take to deal with this, beyond the existing solution of registering custom event handlers when joining a server.

**Comment by wagyourtail** [comment]
anything I would do further would degrade the experience for other sets of use cases, so I'll leave it up to the user to figure this out. I provide them with enough details to do their own filtering
